# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class Api:
        name: str
        type: str
        url: str
    class App:
        name: str
        stage: str
    class AppSite:
        type: str
        url: str
    class Auth:
        type: str
        url: str
    class Bus:
        arn: str
        name: str
        type: str
    class DatabaseMigrator:
        name: str
        type: str
    class DiscordClientId:
        type: str
        value: str
    class DiscordClientSecret:
        type: str
        value: str
    class NeonDatabaseUrl:
        type: str
        value: str

